PS C:\> Add-PSSnapIn -Name Microsoft.Exchange, Microsoft.Windows.AD

# Replace siteurl with actual web url
$web = Connect-PnPOnline –Url https://unitednations.sharepoint.com/sites/DOS-HRM-SAS –UseWebLogin
# Replace docurl with document library url
$list = get-pnplist

function DeleteFiles {
    param($folderUrl)
    $folder = $web.GetFolder($folderUrl)
    foreach ($file in $folder.Files) {
        # Delete file by deleting parent SPListItem
        Write-Host("DELETED FILE: " + $file.name)
        $list.Items.DeleteItemById($file.Item.Id)
    }
}

# Delete root files
DeleteFiles($list.RootFolder.Url)

# Delete files in folders
foreach ($folder in $list.Folders) {
    DeleteFiles($folder.Url)
}

# Delete folders
foreach ($folder in $list.Folders) {
    try {
        Write-Host("DELETED FOLDER: " + $folder.name)
        $list.Folders.DeleteItemById($folder.ID)
    }
    catch {
        # Deletion of parent folder already deleted this folder
    }
}

Connect-PnPOnline –Url https://unitednations.sharepoint.com/sites/DOS-HRM-SAS –UseWebLogin
Get-Command -Module *PnP*


CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Alias           Add-PnPPnPProvisioningSubSite                      3.8.1904.0 SharePointPnPPowerShellOnline
Alias           Add-PnPProvisioningSequence                        3.8.1904.0 SharePointPnPPowerShellOnline
Alias           Add-PnPProvisioningSite                            3.8.1904.0 SharePointPnPPowerShellOnline
Alias           Apply-PnPProvisioningHierarchy                     3.8.1904.0 SharePointPnPPowerShellOnline
Alias           Connect-PnPHubSite                                 3.8.1904.0 SharePointPnPPowerShellOnline
Alias           Disconnect-PnPHubSite                              3.8.1904.0 SharePointPnPPowerShellOnline
Alias           Ensure-PnPFolder                                   3.8.1904.0 SharePointPnPPowerShellOnline
Alias           Execute-PnPQuery                                   3.8.1904.0 SharePointPnPPowerShellOnline
Alias           Get-PnPProvisioningSequence                        3.8.1904.0 SharePointPnPPowerShellOnline
Alias           Get-PnPProvisioningSite                            3.8.1904.0 SharePointPnPPowerShellOnline
Alias           Load-PnPProvisioningTemplate                       3.8.1904.0 SharePointPnPPowerShellOnline
Alias           New-PnPProvisioningCommunicationSite               3.8.1904.0 SharePointPnPPowerShellOnline
Alias           New-PnPProvisioningHierarchy                       3.8.1904.0 SharePointPnPPowerShellOnline
Alias           New-PnPProvisioningSequence                        3.8.1904.0 SharePointPnPPowerShellOnline
Alias           New-PnPProvisioningTeamNoGroupSite                 3.8.1904.0 SharePointPnPPowerShellOnline
Alias           New-PnPProvisioningTeamNoGroupSubSite              3.8.1904.0 SharePointPnPPowerShellOnline
Alias           New-PnPProvisioningTeamSite                        3.8.1904.0 SharePointPnPPowerShellOnline
Alias           Read-PnPProvisioningHierarchy                      3.8.1904.0 SharePointPnPPowerShellOnline
Alias           Save-PnPProvisioningHierarchy                      3.8.1904.0 SharePointPnPPowerShellOnline
Alias           Test-PnPProvisioningHierarchy                      3.8.1904.0 SharePointPnPPowerShellOnline
Function        Disable-PnpDevice                                  1.0.0.0    PnpDevice
Function        Enable-PnpDevice                                   1.0.0.0    PnpDevice
Function        Get-PnpDevice                                      1.0.0.0    PnpDevice
Function        Get-PnpDeviceProperty                              1.0.0.0    PnpDevice
Cmdlet          Add-PnPAlert                                       3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPApp                                         3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPClientSidePage                              3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPClientSidePageSection                       3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPClientSideText                              3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPClientSideWebPart                           3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPContentType                                 3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPContentTypeToDocumentSet                    3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPContentTypeToList                           3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPCustomAction                                3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPDataRowsToProvisioningTemplate              3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPDocumentSet                                 3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPEventReceiver                               3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPField                                       3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPFieldFromXml                                3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPFieldToContentType                          3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPFile                                        3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPFileToProvisioningTemplate                  3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPFolder                                      3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPHtmlPublishingPageLayout                    3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPHubSiteAssociation                          3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPIndexedProperty                             3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPJavaScriptBlock                             3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPJavaScriptLink                              3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPListFoldersToProvisioningTemplate           3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPListItem                                    3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPMasterPage                                  3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPNavigationNode                              3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPOffice365GroupToSite                        3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPProvisioningTemplate                        3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPPublishingImageRendition                    3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPPublishingPage                              3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPPublishingPageLayout                        3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPRoleDefinition                              3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPSiteClassification                          3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPSiteCollectionAdmin                         3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPSiteCollectionAppCatalog                    3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPSiteDesign                                  3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPSiteDesignTask                              3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPSiteScript                                  3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPStoredCredential                            3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPTaxonomyField                               3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPTenantCdnOrigin                             3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPTenantSequence                              3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPTenantSequenceSite                          3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPTenantSequenceSubSite                       3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPTenantTheme                                 3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPUserToGroup                                 3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPView                                        3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPWebhookSubscription                         3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPWebPartToWebPartPage                        3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPWebPartToWikiPage                           3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPWikiPage                                    3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPWorkflowDefinition                          3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Add-PnPWorkflowSubscription                        3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Apply-PnPProvisioningTemplate                      3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Apply-PnPTenantTemplate                            3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Approve-PnPTenantServicePrincipalPermissionRequest 3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Clear-PnPDefaultColumnValues                       3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Clear-PnPListItemAsRecord                          3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Clear-PnPRecycleBinItem                            3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Clear-PnPTenantRecycleBinItem                      3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Connect-PnPMicrosoftGraph                          3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Connect-PnPOnline                                  3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Convert-PnPFolderToProvisioningTemplate            3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Convert-PnPProvisioningTemplate                    3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          ConvertTo-PnPClientSidePage                        3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Copy-PnPFile                                       3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Copy-PnPItemProxy                                  3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Deny-PnPTenantServicePrincipalPermissionRequest    3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Disable-PnPFeature                                 3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Disable-PnPInPlaceRecordsManagementForSite         3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Disable-PnPPowerShellTelemetry                     3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Disable-PnPResponsiveUI                            3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Disable-PnPSiteClassification                      3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Disable-PnPTenantServicePrincipal                  3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Disconnect-PnPOnline                               3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Enable-PnPFeature                                  3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Enable-PnPInPlaceRecordsManagementForSite          3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Enable-PnPPowerShellTelemetry                      3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Enable-PnPResponsiveUI                             3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Enable-PnPSiteClassification                       3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Enable-PnPTenantServicePrincipal                   3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Export-PnPClientSidePage                           3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Export-PnPClientSidePageMapping                    3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Export-PnPTaxonomy                                 3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Export-PnPTermGroupToXml                           3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Find-PnPFile                                       3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPAccessToken                                 3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPAlert                                       3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPApp                                         3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPAppAuthAccessToken                          3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPAppInstance                                 3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPAuditing                                    3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPAuthenticationRealm                         3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPAvailableClientSideComponents               3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPAzureADManifestKeyCredentials               3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPAzureCertificate                            3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPClientSideComponent                         3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPClientSidePage                              3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPConnection                                  3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPContentType                                 3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPContentTypePublishingHubUrl                 3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPContext                                     3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPCustomAction                                3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPDefaultColumnValues                         3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPDocumentSetTemplate                         3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPEventReceiver                               3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPException                                   3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPFeature                                     3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPField                                       3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPFile                                        3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPFolder                                      3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPFolderItem                                  3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPGroup                                       3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPGroupMembers                                3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPGroupPermissions                            3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPHealthScore                                 3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPHideDefaultThemes                           3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPHomePage                                    3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPHomeSite                                    3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPHubSite                                     3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPIndexedPropertyKeys                         3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPInPlaceRecordsManagement                    3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPJavaScriptLink                              3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPLabel                                       3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPList                                        3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPListInformationRightsManagement             3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPListItem                                    3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPListRecordDeclaration                       3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPMasterPage                                  3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPNavigationNode                              3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPPowerShellTelemetryEnabled                  3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPProperty                                    3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPPropertyBag                                 3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPProvisioningTemplate                        3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPProvisioningTemplateFromGallery             3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPPublishingImageRendition                    3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPRecycleBinItem                              3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPRequestAccessEmails                         3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPRoleDefinition                              3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPSearchConfiguration                         3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPSearchCrawlLog                              3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPSite                                        3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPSiteClassification                          3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPSiteClosure                                 3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPSiteCollectionAdmin                         3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPSiteCollectionTermStore                     3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPSiteDesign                                  3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPSiteDesignRights                            3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPSiteDesignRun                               3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPSiteDesignRunStatus                         3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPSiteDesignTask                              3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPSitePolicy                                  3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPSiteScript                                  3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPSiteSearchQueryResults                      3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPStorageEntity                               3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPStoredCredential                            3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPSubWebs                                     3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPTaxonomyItem                                3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPTaxonomySession                             3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPTenant                                      3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPTenantAppCatalogUrl                         3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPTenantCdnEnabled                            3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPTenantCdnOrigin                             3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPTenantCdnPolicies                           3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPTenantRecycleBinItem                        3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPTenantSequence                              3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPTenantSequenceSite                          3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPTenantServicePrincipal                      3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPTenantServicePrincipalPermissionGrants      3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPTenantServicePrincipalPermissionRequests    3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPTenantSite                                  3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPTenantTheme                                 3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPTerm                                        3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPTermGroup                                   3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPTermSet                                     3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPTheme                                       3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPTimeZoneId                                  3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPUnifiedGroup                                3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPUnifiedGroupMembers                         3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPUnifiedGroupOwners                          3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPUPABulkImportStatus                         3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPUser                                        3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPUserProfileProperty                         3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPView                                        3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPWeb                                         3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPWebhookSubscriptions                        3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPWebPart                                     3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPWebPartProperty                             3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPWebPartXml                                  3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPWebTemplates                                3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPWikiPageContent                             3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPWorkflowDefinition                          3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPWorkflowInstance                            3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Get-PnPWorkflowSubscription                        3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Grant-PnPHubSiteRights                             3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Grant-PnPSiteDesignRights                          3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Grant-PnPTenantServicePrincipalPermission          3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Import-PnPAppPackage                               3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Import-PnPTaxonomy                                 3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Import-PnPTermGroupFromXml                         3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Import-PnPTermSet                                  3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Install-PnPApp                                     3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Install-PnPSolution                                3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Invoke-PnPQuery                                    3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Invoke-PnPSiteDesign                               3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Invoke-PnPWebAction                                3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Measure-PnPList                                    3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Measure-PnPResponseTime                            3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Measure-PnPWeb                                     3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Move-PnPClientSideComponent                        3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Move-PnPFile                                       3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Move-PnPFolder                                     3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Move-PnPItemProxy                                  3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Move-PnPListItemToRecycleBin                       3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Move-PnPRecycleBinItem                             3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          New-PnPAzureCertificate                            3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          New-PnPExtensibilityHandlerObject                  3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          New-PnPGroup                                       3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          New-PnPList                                        3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          New-PnPPersonalSite                                3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          New-PnPProvisioningTemplate                        3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          New-PnPProvisioningTemplateFromFolder              3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          New-PnPSite                                        3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          New-PnPTenantSequence                              3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          New-PnPTenantSequenceCommunicationSite             3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          New-PnPTenantSequenceTeamNoGroupSite               3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          New-PnPTenantSequenceTeamNoGroupSubSite            3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          New-PnPTenantSequenceTeamSite                      3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          New-PnPTenantSite                                  3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          New-PnPTenantTemplate                              3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          New-PnPTerm                                        3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          New-PnPTermGroup                                   3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          New-PnPTermSet                                     3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          New-PnPUnifiedGroup                                3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          New-PnPUPABulkImportJob                            3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          New-PnPUser                                        3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          New-PnPWeb                                         3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Publish-PnPApp                                     3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Read-PnPProvisioningTemplate                       3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Read-PnPTenantTemplate                             3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Register-PnPHubSite                                3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPAlert                                    3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPApp                                      3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPClientSideComponent                      3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPClientSidePage                           3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPContentType                              3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPContentTypeFromDocumentSet               3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPContentTypeFromList                      3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPCustomAction                             3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPEventReceiver                            3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPField                                    3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPFieldFromContentType                     3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPFile                                     3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPFileFromProvisioningTemplate             3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPFolder                                   3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPGroup                                    3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPHomeSite                                 3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPHubSiteAssociation                       3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPIndexedProperty                          3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPJavaScriptLink                           3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPList                                     3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPListItem                                 3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPNavigationNode                           3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPPropertyBagValue                         3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPPublishingImageRendition                 3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPRoleDefinition                           3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPSearchConfiguration                      3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPSiteClassification                       3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPSiteCollectionAdmin                      3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPSiteCollectionAppCatalog                 3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPSiteDesign                               3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPSiteDesignTask                           3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPSiteScript                               3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPStorageEntity                            3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPStoredCredential                         3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPTaxonomyItem                             3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPTenantCdnOrigin                          3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPTenantSite                               3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPTenantTheme                              3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPTermGroup                                3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPUnifiedGroup                             3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPUser                                     3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPUserFromGroup                            3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPView                                     3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPWeb                                      3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPWebhookSubscription                      3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPWebPart                                  3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPWikiPage                                 3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPWorkflowDefinition                       3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Remove-PnPWorkflowSubscription                     3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Rename-PnPFile                                     3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Rename-PnPFolder                                   3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Request-PnPReIndexList                             3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Request-PnPReIndexWeb                              3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Reset-PnPFileVersion                               3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Resolve-PnPFolder                                  3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Restore-PnPRecycleBinItem                          3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Restore-PnPTenantRecycleBinItem                    3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Resume-PnPWorkflowInstance                         3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Revoke-PnPSiteDesignRights                         3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Revoke-PnPTenantServicePrincipalPermission         3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Save-PnPProvisioningTemplate                       3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Save-PnPTenantTemplate                             3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Send-PnPMail                                       3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPAppSideLoading                              3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPAuditing                                    3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPAvailablePageLayouts                        3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPClientSidePage                              3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPClientSideText                              3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPClientSideWebPart                           3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPContext                                     3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPDefaultColumnValues                         3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPDefaultContentTypeToList                    3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPDefaultPageLayout                           3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPDocumentSetField                            3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPField                                       3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPFileCheckedIn                               3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPFileCheckedOut                              3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPGroup                                       3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPGroupPermissions                            3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPHideDefaultThemes                           3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPHomePage                                    3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPHomeSite                                    3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPHubSite                                     3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPIndexedProperties                           3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPInPlaceRecordsManagement                    3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPLabel                                       3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPList                                        3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPListInformationRightsManagement             3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPListItem                                    3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPListItemAsRecord                            3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPListItemPermission                          3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPListPermission                              3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPListRecordDeclaration                       3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPMasterPage                                  3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPMinimalDownloadStrategy                     3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPPropertyBagValue                            3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPProvisioningTemplateMetadata                3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPRequestAccessEmails                         3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPSearchConfiguration                         3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPSite                                        3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPSiteClosure                                 3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPSiteDesign                                  3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPSitePolicy                                  3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPSiteScript                                  3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPStorageEntity                               3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPTaxonomyFieldValue                          3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPTenant                                      3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPTenantCdnEnabled                            3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPTenantCdnPolicy                             3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPTenantSite                                  3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPTheme                                       3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPTraceLog                                    3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPUnifiedGroup                                3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPUserProfileProperty                         3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPView                                        3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPWeb                                         3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPWebhookSubscription                         3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPWebPartProperty                             3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPWebPermission                               3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPWebTheme                                    3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Set-PnPWikiPageContent                             3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Start-PnPWorkflowInstance                          3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Stop-PnPWorkflowInstance                           3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Submit-PnPSearchQuery                              3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Sync-PnPAppToTeams                                 3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Test-PnPListItemIsRecord                           3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Test-PnPOffice365GroupAliasIsUsed                  3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Test-PnPTenantTemplate                             3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Uninstall-PnPApp                                   3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Uninstall-PnPAppInstance                           3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Uninstall-PnPSolution                              3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Unpublish-PnPApp                                   3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Unregister-PnPHubSite                              3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Update-PnPApp                                      3.8.1904.0 SharePointPnPPowerShellOnline
Cmdlet          Update-PnPSiteClassification                       3.8.1904.0 SharePointPnPPowerShellOnline